### PR TITLE
Fix initiative, defense, and add item qualities

### PR DESCRIPTION
**Pull request by Khaali-dev**
Hello,

thanks for taking on the symbaroum system for foundry VTT project.

I have made a few changes to the code:
- Initiative. Now you can change the attribute for initiative for each actor, since several talents can do this, Default is "quick"
- Defense. Now you can change the attribute for defense for each actor, default is "quick"
- Item qualities. Added a tab in the weapon sheet with all mundane qualities as check boxes. This is more practical than an unique string, and very useful for macros.

### CODE REVIEW

**Comment by pwatson100** [comment]
Wow.  Many thanks.  I am still getting to grips with the code so this is really useful.

**Comment by pwatson100** [comment]
Are you on Discord?  If so can you DM me please so I can credit you in the next release for the work you have done on the system.

**Comment by Khaali-dev** [comment]
Thanks! Yes I am on discord : khaali#8262

I am currently working on macros for symbaroum, 
an attack macro that integrate abilities, weapon qualities, status effects (poison...), ...
and a power casting macro that also integrates abilities, status effects, etc.

work in progress is here:
https://github.com/Khaali-dev/Symbaroum-FoundryVTT-Macros  (sorry the output is in french for now)

**Comment by pwatson100** [comment]
One of the enhancements I was/am interested in doing is having the weapon qualities automatically update the relevant mods.  So the first step was to do exactly what you have just done and add a tab with check boxes for each of the qualities.  I like the initiative change as well.  Though I can imagine some people complaining about having a roll of 30027 :)

**Pull request merged**
