### PR TITLE
prepareRollAttribute resolves when roll completes

### PR DESCRIPTION
**Pull request by MiddleTwin**
Cherrypicked the commit from #608 to RT-V10 as requested.

### CODE REVIEW

**Comment by MiddleTwin** [comment]
Note that I haven't tested on this branch, I can do that in a few hours.

**Comment by MiddleTwin** [comment]
Alright, since the function is way too complicated to do a thorough branch test on I'll just try and test each line I changed- i.e. each terminal state. I also found another one that I missed initially (resist rolls).

- [ ] Standard attribute roll
- [ ] Dialog box is cancelled
- Combat automation for:
  - [ ] PC weapon attack
  - [ ] PC armor roll
  - [ ] NPC weapon attack (no resist rolls)
  - [ ] NPC weapon attack (resist rolls)
- [] Invalid damage modifier

Tests will be run with the following script macro:

```js
let actor = game.actor.get(<id>)
actor.doThing().then(val => ChatMessage.create({content: JSON.stringify(val)}))
```

I will be testing the following behavior:
1) Chat message does not appear until *after* the roll
2) Chat message contains useful data about the roll
3) If roll doesn't happen chat message should not appear

The current system fails all three tests for all the listed cases AFAICT.
Results will be posted soon.

**Comment by MiddleTwin** [comment]
RESULTS: (S: succeed, F: fail, blank: N/A)

| Case | Test 1 | Test 2 | Test 3 |
-------|--------|--------|--------
| Standard Attribute Roll | S | S | |
| Roll Dialog Cancelled | | | S |
| PC attack (using actor.rollWeapon) | F | F | |
| PC armor roll (using actor.rollArmor) | S | S | |
| NPC Weapon attack, no resist roll | F | F | |
| NPC Weapon attack, resist roll | F | F | |
| Invalid damage modifier <Couldn't trigger> | | | |

Overall: does not work on attacks. I will try to push a commit to fix that, at least for the no-resist-roll case

**Comment by MiddleTwin** [comment]
Take 2:
Attacks were in a separate function for enhanced combat. I edited that as well.

| Case | Test 1 | Test 2 | Test 3 |
-------|--------|--------|--------
| Standard Attribute Roll | S | S | |
| Roll Dialog Cancelled | | | S |
| PC attack (using actor.rollWeapon) | S | S | |
| PC armor roll (using actor.rollArmor) | S | S | |
| NPC Weapon attack, no resist roll | S | S | |
| NPC Weapon attack, resist roll | S | S | |

Note that although the NPC attack was fine with resist rolls I'm pretty sure it shouldn't have-probably tested resist rolls wrong. Still, good enough for me to be happy.

**Review by bithir — APPROVED** [review]
Looks like reasonable changes to me.

I suggest we merge after v11 branch have been merged to master - have a bit of play with this, and then merge that this too before release.

**Pull request merged**
